server:
  port: 8000
  tomcat:
    uri-encoding: UTF-8
spring:
  datasource:
    username: root
    password:
    max-idle: 10
    min-idle: 5
    initial-size: 5
    driver-class-name: com.mysql.jdbc.Driver
    max-wait: 10000
    url: jdbc:mysql://localhost:3306/clnews?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8

mybatis:
  mapper-locations: classpath:mybatis/*.xml

news:
  toutiao:
    main_url: https://www.toutiao.com
    news_hot_url: https://www.toutiao.com/ch/news_hot/